Repository bigbite/benenson, pull requests merged in 2018-12, with the labels that each got.

#31 Add readme.txt
  readme.txt
Labels: enhancement

#35 Adds fix for social icons missing
  src/styles/components/_social.scss
  src/styles/layout/_page-foot.scss
Labels: bug

#36 Remove unused vars
  page-fullwidth.php
  page.php
Labels: chore

#37 Remove sudo: false from .travis.yml
  .travis.yml
Labels: chore

#39 Adjust a11y function bail precedence
  includes/accessibility.php
Labels: chore
