Repository bigbite/benenson, pull requests merged in 2019-02, with the labels that each got.

#135 Adds fix for template lock on key facts
  src/scripts/blocks/key-facts/index.js
Labels: [block] Key Facts, bug

#119 Remove unused file
  src/scripts/blocks/post-list/components/DisplayCategoriesDeprecated.js
Labels: chore

#117 Implement fix for overlapping social icon links in footer
  src/styles/components/_social.scss
Labels: bug, chore

#125 Remove package-lock.json
  package-lock.json
Labels: chore

#122 Fix class instance check
  includes/disable-rest-api.php
Labels: bug, chore

#123 Remove unnecessary namespace escape
  includes/theme-setup.php
Labels: chore

#124 Remove unnecessary whitespace
  includes/theme-setup.php
Labels: chore
